rabbitmq:
  image: rabbitmq:management
  ports:
    - 5672:5672
    - 8080:15672
  container_name: rabbitmq
  environment:
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: admin
  hostname: rabbit01